name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts (with thumbnails)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in posts with thumbnails
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://hendynoize.net/feed/"
          max_post_count: 6
          template: |
            <div style="display:flex; gap:16px; flex-wrap:wrap;">
              $posts
            </div>

          post_template: |
            <a href="$url" style="text-decoration:none; width:160px; display:block;">
              <img src="$thumbnail" alt="$title" style="width:100%; border-radius:10px;">
              <div style="margin-top:6px; font-weight:bold; font-size:14px; color:#333;">
                $title
              </div>
            </a>
